// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface ArticlePageStoryblok {
  Name?: string;
  Bilde?: AssetStoryblok;
  component: "article page";
  _uid: string;
  [k: string]: any;
}

export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (ArticlePageStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (ArticlePageStoryblok | FeatureStoryblok | GridStoryblok | PageStoryblok | TeaserStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}
